### PR TITLE
Add new stage:draft key/value pair allowing to exclude draft PRs

### LINKED ISSUE #262: RFE: exclude PRs that are drafts
GitHub introduced draft PRs a while ago:
https://github.blog/2019-02-14-introducing-draft-pull-requests/

It would be great if draft mode worked like `--exclude`!

### PR DESCRIPTION
**Pull request by sbesson**
Fixes #262 

This is a simple expansion of the key/value filter infrastructure that allow to test the draft attribute of a Pull Request and exclude it from the merge candidates. The default `org` set of filters is modified to exclude draft PRs by default.

For testing, first install this branch e.g. in a virtual environment

```
source venv/bin/activate
pip install -e .
```

Then run the command against a repository against which Pull Requests in a draft stage are opened e.g. https://github.com/ome/bioformats/pulls. The default set of filters should now exclude these PRs from the merge candidates and indicate the reason in the log output: 

```
scc merge info --master # should filter out draft PRs
scc merge info --master -Dall # should include all PRs including draft PRs

```

Proposed tag: `0.19.0` given the breaking change

### CODE REVIEW

**Review by melissalinkert — APPROVED** [review]
Tested with https://github.com/glencoesoftware/raw2ometiff and https://github.com/ome/bioformats, using `scc merge master --info` and `scc merge develop --info` respectively. Works as expected with and without the `-Dall` option.

**Review by knabar — APPROVED** [review]
Works as intended:

```
$ scc merge --info master
2022-10-12 11:28:32,926 [   scc.merge] INFO  Listing Pull Request(s) based on master
2022-10-12 11:28:32,927 [   scc.merge] INFO  Including Pull Request(s) opened by any public member of the organization
2022-10-12 11:28:32,927 [   scc.merge] INFO  Including Pull Request(s) labelled as include or dependencies
2022-10-12 11:28:32,927 [   scc.merge] INFO  Excluding Pull Request(s) staged as draft
2022-10-12 11:28:32,927 [   scc.merge] INFO  Excluding Pull Request(s) labelled as exclude or breaking
2022-10-12 11:28:35,981 [   scc.merge] INFO  Repository: glencoesoftware/v2-project
2022-10-12 11:28:35,981 [   scc.merge] INFO  Excluded PRs:
2022-10-12 11:28:35,981 [   scc.merge] INFO    - PR 863 knabar 'Test only, don't merge me' (stage: draft)
...
$ scc merge --info master -Dall
2022-10-12 11:28:43,656 [   scc.merge] INFO  Listing Pull Request(s) based on master
2022-10-12 11:28:43,656 [   scc.merge] INFO  Including Pull Request(s) opened by any user
2022-10-12 11:28:46,834 [   scc.merge] INFO  Repository: glencoesoftware/v2-project
2022-10-12 11:28:46,834 [   scc.merge] INFO  Candidate PRs:
2022-10-12 11:28:46,834 [   scc.merge] INFO    - PR 863 knabar 'Test only, don't merge me'
...
```

**Comment by will-moore** [comment]
I've not tested this, but it seems like a good feature (expected behaviour). 👍

**Review by will-moore — APPROVED** [review]

**Review by joshmoore — APPROVED** [review]
> Proposed tag: 0.19.0 given the breaking change

Agreed, though now I feel guilty we never went 1.0 ;)

**Comment by sbesson** [comment]
> Agreed, though now I feel guilty we never went 1.0 ;)

Happy to call the next version 1.0.0 if it's preferable.

**Pull request merged**
